name: rasa-career
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - rasa==3.2.0
    - tensorflow==2.7.0
    - streamlit>=1.24.0
    - nltk==3.8.1
    - pandas==2.0.2
    - numpy==1.24.3
    - scikit-learn==1.2.2
